version: '3.8'
services:
  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=testing
    volumes:
      - postgres-data:/var/lib/postgresql/data
#  admin:
#    image: adminer
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - 8080:8080

volumes:
  postgres-data: